In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

"""import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))"""

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

"import os\nfor dirname, _, filenames in os.walk('/kaggle/input'):\n    for filename in filenames:\n        print(os.path.join(dirname, filename))"

Linear dataset

In [2]:
ANDdata = pd.DataFrame({"A":[0,0,1,1],"B":[0,1,0,1],"C":[0,0,0,1]})
ANDdata.head()

   A  B  C
0  0  0  0
1  0  1  0
2  1  0  0
3  1  1  1

NON-Linear dataset

In [3]:
XORdata = pd.DataFrame({"A":[0,0,1,1],"B":[0,1,0,1],"C":[0,1,1,0]})
XORdata.head()

   A  B  C
0  0  0  0
1  0  1  1
2  1  0  1
3  1  1  0

# Single layer perceptpron

In [26]:
import numpy as np
import pandas as pd


def activation_func(value,actfn = "sigmoid"):    
    if actfn == "sigmoid":
        return (1/(1+np.exp(-value)))
    elif actfn == "tanh":
        return ((np.exp(value)-np.exp(-value))/(np.exp(value)+np.exp(-value)))
    else:
        return max(0,value) #relu

def perceptron_train(in_data,labels,alpha,actfn, bias = False):
    X=np.array(in_data)
    y=np.array(labels)
    weights=np.random.random(X.shape[1])
    
    #if bias:
        ##to be written
    
    original=weights
    
    for epoch in range(10):
        print(f"Epoch {epoch}/10")
        for key in range(X.shape[0]):
            z = np.matmul(np.transpose(weights),X[key])
            a=activation_func(z,actfn)
            yn=0
            if actfn == "sigmoid":    
                if a>=0.5:
                    yn=1
                else:
                    yn=0
            elif actfn == "tanh":
                if a>0:
                    yn=1
                else:
                    yn=0
            else:
                if a>5:
                    yn=1
                else:
                    yn=0
            weights=weights+alpha*(yn-y[key])*X[key]
            print('Iteration '+str(key)+': '+str(weights))
        print('Difference: '+str(weights-original))
    return weights

#  Testing and Score

def perceptron_test(in_data,label_shape,weights,actfn):
    X=np.array(in_data)
    y=np.zeros(label_shape)
    print(f"Testing:")
    for key in range(X.shape[1]):
        z = np.matmul(np.transpose(weights),X[key])
        a=activation_func(z,actfn)
        y[key]=0
        if actfn == "sigmoid":
            if a>=0.5:
                y[key]=1
            else:
                y[key]=0
        elif actfn == "tanh":
            if a>0:
                y[key] = 1
            else:
                y[key] = 0
        else:
            if a>0.3:
                yn=1
            else:
                yn=0
            #print(f"key:{key}\ty:{y}")
    return y
def score(result,labels):
    difference=result-np.array(labels)
    correct_ctr=0
    for elem in range(difference.shape[0]):
        if difference[elem]==0:
            correct_ctr+=1
    score=correct_ctr*100/difference.size
    print('Score='+str(score))

# Linear dataset

## Without bias sigmoid

In [37]:
# Main code

# Dividing d_train into data and labels/targets
d_train_y = ANDdata['C']
d_train_X = ANDdata.drop(['C'], axis=1)

    # Dividing d_train into data and labels/targets
d_test_y = ANDdata['C']
d_test_X = ANDdata.drop(['C'], axis=1)

    # Learning rate
alpha = 0.55

    # Train
weights = perceptron_train(d_train_X, d_train_y, alpha, actfn="sigmoid")

    # Test
result_test = perceptron_test(d_test_X, d_test_y.shape, weights, actfn="sigmoid")

for i in range(len(result_test)):
    print(f"A:{d_test_X.iloc[i][0]}\tB:{d_test_X.iloc[i][1]}\tC:{d_test_y[i]}\tC_pred:{result_test[i]}")

from sklearn.metrics import log_loss
print(f"BCE {log_loss(result_test, d_test_y)}")

    # Calculate score
score(result_test, d_test_y)

Epoch 0/10
Iteration 0: [0.89972628 0.03497059]
Iteration 1: [0.89972628 0.58497059]
Iteration 2: [1.44972628 0.58497059]
Iteration 3: [1.44972628 0.58497059]
Difference: [0.55 0.55]
Epoch 1/10
Iteration 0: [1.44972628 0.58497059]
Iteration 1: [1.44972628 1.13497059]
Iteration 2: [1.99972628 1.13497059]
Iteration 3: [1.99972628 1.13497059]
Difference: [1.1 1.1]
Epoch 2/10
Iteration 0: [1.99972628 1.13497059]
Iteration 1: [1.99972628 1.68497059]
Iteration 2: [2.54972628 1.68497059]
Iteration 3: [2.54972628 1.68497059]
Difference: [1.65 1.65]
Epoch 3/10
Iteration 0: [2.54972628 1.68497059]
Iteration 1: [2.54972628 2.23497059]
Iteration 2: [3.09972628 2.23497059]
Iteration 3: [3.09972628 2.23497059]
Difference: [2.2 2.2]
Epoch 4/10
Iteration 0: [3.09972628 2.23497059]
Iteration 1: [3.09972628 2.78497059]
Iteration 2: [3.64972628 2.78497059]
Iteration 3: [3.64972628 2.78497059]
Difference: [2.75 2.75]
Epoch 5/10
Iteration 0: [3.64972628 2.78497059]
Iteration 1: [3.64972628 3.33497059]
Iteration 2: [4.19972628 3.33497059]
Iteration 3: [4.19972628 3.33497059]
Difference: [3.3 3.3]
Epoch 6/10
Iteration 0: [4.19972628 3.33497059]
Iteration 1: [4.19972628 3.88497059]
Iteration 2: [4.74972628 3.88497059]
Iteration 3: [4.74972628 3.88497059]
Difference: [3.85 3.85]
Epoch 7/10
Iteration 0: [4.74972628 3.88497059]
Iteration 1: [4.74972628 4.43497059]
Iteration 2: [5.29972628 4.43497059]
Iteration 3: [5.29972628 4.43497059]
Difference: [4.4 4.4]
Epoch 8/10
Iteration 0: [5.29972628 4.43497059]
Iteration 1: [5.29972628 4.98497059]
Iteration 2: [5.84972628 4.98497059]
Iteration 3: [5.84972628 4.98497059]
Difference: [4.95 4.95]
Epoch 9/10
Iteration 0: [5.84972628 4.98497059]
Iteration 1: [5.84972628 5.53497059]
Iteration 2: [6.39972628 5.53497059]
Iteration 3: [6.39972628 5.53497059]
Difference: [5.5 5.5]
Testing:
A:0	B:0	C:0	C_pred:1.0
A:0	B:1	C:0	C_pred:1.0
A:1	B:0	C:0	C_pred:0.0
A:1	B:1	C:1	C_pred:0.0
BCE 27.032740041837865
Score=25.0

## With bias Sigmoid

In [38]:
d_train_X["bias"] = [1,1,1,1]

In [39]:
d_train_X

   A  B  bias
0  0  0     1
1  0  1     1
2  1  0     1
3  1  1     1

In [40]:
# Main code

# Dividing d_train into data and labels/targets
d_train_y = ANDdata['C']
d_train_X = ANDdata.drop(['C'], axis=1)
d_train_X["bias"] = [0.1,.1,.1,.1]

    # Dividing d_train into data and labels/targets
d_test_y = d_train_y
d_test_X = d_train_X

    # Learning rate
alpha = .9

    # Train
weights = perceptron_train(d_train_X, d_train_y, alpha, actfn="sigmoid")

    # Test
result_test = perceptron_test(d_test_X, d_test_y.shape, weights, actfn="sigmoid")

for i in range(len(result_test)):
    print(f"A:{d_test_X.iloc[i][0]}\tB:{d_test_X.iloc[i][1]}\tC:{d_test_y[i]}\tC_pred:{result_test[i]}")

from sklearn.metrics import log_loss
print(f"BCE {log_loss(result_test, d_test_y)}")

    # Calculate score
score(result_test, d_test_y)

Epoch 0/10
Iteration 0: [0.65014949 0.7820929  0.75512224]
Iteration 1: [0.65014949 1.6820929  0.84512224]
Iteration 2: [1.55014949 1.6820929  0.93512224]
Iteration 3: [1.55014949 1.6820929  0.93512224]
Difference: [0.9  0.9  0.27]
Epoch 1/10
Iteration 0: [1.55014949 1.6820929  1.02512224]
Iteration 1: [1.55014949 2.5820929  1.11512224]
Iteration 2: [2.45014949 2.5820929  1.20512224]
Iteration 3: [2.45014949 2.5820929  1.20512224]
Difference: [1.8  1.8  0.54]
Epoch 2/10
Iteration 0: [2.45014949 2.5820929  1.29512224]
Iteration 1: [2.45014949 3.4820929  1.38512224]
Iteration 2: [3.35014949 3.4820929  1.47512224]
Iteration 3: [3.35014949 3.4820929  1.47512224]
Difference: [2.7  2.7  0.81]
Epoch 3/10
Iteration 0: [3.35014949 3.4820929  1.56512224]
Iteration 1: [3.35014949 4.3820929  1.65512224]
Iteration 2: [4.25014949 4.3820929  1.74512224]
Iteration 3: [4.25014949 4.3820929  1.74512224]
Difference: [3.6  3.6  1.08]
Epoch 4/10
Iteration 0: [4.25014949 4.3820929  1.83512224]
Iteration 1: [4.25014949 5.2820929  1.92512224]
Iteration 2: [5.15014949 5.2820929  2.01512224]
Iteration 3: [5.15014949 5.2820929  2.01512224]
Difference: [4.5  4.5  1.35]
Epoch 5/10
Iteration 0: [5.15014949 5.2820929  2.10512224]
Iteration 1: [5.15014949 6.1820929  2.19512224]
Iteration 2: [6.05014949 6.1820929  2.28512224]
Iteration 3: [6.05014949 6.1820929  2.28512224]
Difference: [5.4  5.4  1.62]
Epoch 6/10
Iteration 0: [6.05014949 6.1820929  2.37512224]
Iteration 1: [6.05014949 7.0820929  2.46512224]
Iteration 2: [6.95014949 7.0820929  2.55512224]
Iteration 3: [6.95014949 7.0820929  2.55512224]
Difference: [6.3  6.3  1.89]
Epoch 7/10
Iteration 0: [6.95014949 7.0820929  2.64512224]
Iteration 1: [6.95014949 7.9820929  2.73512224]
Iteration 2: [7.85014949 7.9820929  2.82512224]
Iteration 3: [7.85014949 7.9820929  2.82512224]
Difference: [7.2  7.2  2.16]
Epoch 8/10
Iteration 0: [7.85014949 7.9820929  2.91512224]
Iteration 1: [7.85014949 8.8820929  3.00512224]
Iteration 2: [8.75014949 8.8820929  3.09512224]
Iteration 3: [8.75014949 8.8820929  3.09512224]
Difference: [8.1  8.1  2.43]
Epoch 9/10
Iteration 0: [8.75014949 8.8820929  3.18512224]
Iteration 1: [8.75014949 9.7820929  3.27512224]
Iteration 2: [9.65014949 9.7820929  3.36512224]
Iteration 3: [9.65014949 9.7820929  3.36512224]
Difference: [9.  9.  2.7]
Testing:
A:0.0	B:0.0	C:0	C_pred:1.0
A:0.0	B:1.0	C:0	C_pred:1.0
A:1.0	B:0.0	C:0	C_pred:1.0
A:1.0	B:1.0	C:1	C_pred:0.0
BCE 36.04365338911715
Score=0.0

## Without bias tanh

In [41]:
# Main code

# Dividing d_train into data and labels/targets
d_train_y = ANDdata['C']
d_train_X = ANDdata.drop(['C'], axis=1)

    # Dividing d_train into data and labels/targets
d_test_y = ANDdata['C']
d_test_X = ANDdata.drop(['C'], axis=1)

    # Learning rate
alpha = .55

    # Train
weights = perceptron_train(d_train_X, d_train_y, alpha, actfn="tanh")

    # Test
result_test = perceptron_test(d_test_X, d_test_y.shape, weights, actfn="tanh")

for i in range(len(result_test)):
    print(f"A:{d_test_X.iloc[i][0]}\tB:{d_test_X.iloc[i][1]}\tC:{d_test_y[i]}\tC_pred:{result_test[i]}")


from sklearn.metrics import log_loss
print(f"BCE {log_loss(result_test, d_test_y)}")

    # Calculate score
score(result_test, d_test_y)

Epoch 0/10
Iteration 0: [0.14972924 0.18718981]
Iteration 1: [0.14972924 0.73718981]
Iteration 2: [0.69972924 0.73718981]
Iteration 3: [0.69972924 0.73718981]
Difference: [0.55 0.55]
Epoch 1/10
Iteration 0: [0.69972924 0.73718981]
Iteration 1: [0.69972924 1.28718981]
Iteration 2: [1.24972924 1.28718981]
Iteration 3: [1.24972924 1.28718981]
Difference: [1.1 1.1]
Epoch 2/10
Iteration 0: [1.24972924 1.28718981]
Iteration 1: [1.24972924 1.83718981]
Iteration 2: [1.79972924 1.83718981]
Iteration 3: [1.79972924 1.83718981]
Difference: [1.65 1.65]
Epoch 3/10
Iteration 0: [1.79972924 1.83718981]
Iteration 1: [1.79972924 2.38718981]
Iteration 2: [2.34972924 2.38718981]
Iteration 3: [2.34972924 2.38718981]
Difference: [2.2 2.2]
Epoch 4/10
Iteration 0: [2.34972924 2.38718981]
Iteration 1: [2.34972924 2.93718981]
Iteration 2: [2.89972924 2.93718981]
Iteration 3: [2.89972924 2.93718981]
Difference: [2.75 2.75]
Epoch 5/10
Iteration 0: [2.89972924 2.93718981]
Iteration 1: [2.89972924 3.48718981]
Iteration 2: [3.44972924 3.48718981]
Iteration 3: [3.44972924 3.48718981]
Difference: [3.3 3.3]
Epoch 6/10
Iteration 0: [3.44972924 3.48718981]
Iteration 1: [3.44972924 4.03718981]
Iteration 2: [3.99972924 4.03718981]
Iteration 3: [3.99972924 4.03718981]
Difference: [3.85 3.85]
Epoch 7/10
Iteration 0: [3.99972924 4.03718981]
Iteration 1: [3.99972924 4.58718981]
Iteration 2: [4.54972924 4.58718981]
Iteration 3: [4.54972924 4.58718981]
Difference: [4.4 4.4]
Epoch 8/10
Iteration 0: [4.54972924 4.58718981]
Iteration 1: [4.54972924 5.13718981]
Iteration 2: [5.09972924 5.13718981]
Iteration 3: [5.09972924 5.13718981]
Difference: [4.95 4.95]
Epoch 9/10
Iteration 0: [5.09972924 5.13718981]
Iteration 1: [5.09972924 5.68718981]
Iteration 2: [5.64972924 5.68718981]
Iteration 3: [5.64972924 5.68718981]
Difference: [5.5 5.5]
Testing:
A:0	B:0	C:0	C_pred:0.0
A:0	B:1	C:0	C_pred:1.0
A:1	B:0	C:0	C_pred:0.0
A:1	B:1	C:1	C_pred:0.0
BCE 18.021826694558577
Score=50.0

## With bias tanh

In [42]:
# Main code

# Dividing d_train into data and labels/targets
d_train_y = ANDdata['C']
d_train_X = ANDdata.drop(['C'], axis=1)
d_train_X["bias"] = [1,1,1,1]
    # Dividing d_train into data and labels/targets
d_test_y = d_train_y
d_test_X = d_train_X

    # Learning rate
alpha = 1.5

    # Train
weights = perceptron_train(d_train_X, d_train_y, alpha, actfn="tanh")

    # Test
result_test = perceptron_test(d_test_X, d_test_y.shape, weights, actfn="tanh")

for i in range(len(result_test)):
    print(f"A:{d_test_X.iloc[i][0]}\tB:{d_test_X.iloc[i][1]}\tC:{d_test_y[i]}\tC_pred:{result_test[i]}")


from sklearn.metrics import log_loss
print(f"BCE {log_loss(result_test, d_test_y)}")

    # Calculate score
score(result_test, d_test_y)

Epoch 0/10
Iteration 0: [0.77623368 0.06692041 2.08346551]
Iteration 1: [0.77623368 1.56692041 3.58346551]
Iteration 2: [2.27623368 1.56692041 5.08346551]
Iteration 3: [2.27623368 1.56692041 5.08346551]
Difference: [1.5 1.5 4.5]
Epoch 1/10
Iteration 0: [2.27623368 1.56692041 6.58346551]
Iteration 1: [2.27623368 3.06692041 8.08346551]
Iteration 2: [3.77623368 3.06692041 9.58346551]
Iteration 3: [3.77623368 3.06692041 9.58346551]
Difference: [3. 3. 9.]
Epoch 2/10
Iteration 0: [ 3.77623368  3.06692041 11.08346551]
Iteration 1: [ 3.77623368  4.56692041 12.58346551]
Iteration 2: [ 5.27623368  4.56692041 14.08346551]
Iteration 3: [ 5.27623368  4.56692041 14.08346551]
Difference: [ 4.5  4.5 13.5]
Epoch 3/10
Iteration 0: [ 5.27623368  4.56692041 15.58346551]
Iteration 1: [ 5.27623368  6.06692041 17.08346551]
Iteration 2: [ 6.77623368  6.06692041 18.58346551]
Iteration 3: [ 6.77623368  6.06692041 18.58346551]
Difference: [ 6.  6. 18.]
Epoch 4/10
Iteration 0: [ 6.77623368  6.06692041 20.08346551]
Iteration 1: [ 6.77623368  7.56692041 21.58346551]
Iteration 2: [ 8.27623368  7.56692041 23.08346551]
Iteration 3: [ 8.27623368  7.56692041 23.08346551]
Difference: [ 7.5  7.5 22.5]
Epoch 5/10
Iteration 0: [ 8.27623368  7.56692041 24.58346551]
Iteration 1: [ 8.27623368  9.06692041 26.08346551]
Iteration 2: [ 9.77623368  9.06692041 27.58346551]
Iteration 3: [ 9.77623368  9.06692041 27.58346551]
Difference: [ 9.  9. 27.]
Epoch 6/10
Iteration 0: [ 9.77623368  9.06692041 29.08346551]
Iteration 1: [ 9.77623368 10.56692041 30.58346551]
Iteration 2: [11.27623368 10.56692041 32.08346551]
Iteration 3: [11.27623368 10.56692041 32.08346551]
Difference: [10.5 10.5 31.5]
Epoch 7/10
Iteration 0: [11.27623368 10.56692041 33.58346551]
Iteration 1: [11.27623368 12.06692041 35.08346551]
Iteration 2: [12.77623368 12.06692041 36.58346551]
Iteration 3: [12.77623368 12.06692041 36.58346551]
Difference: [12. 12. 36.]
Epoch 8/10
Iteration 0: [12.77623368 12.06692041 38.08346551]
Iteration 1: [12.77623368 13.56692041 39.58346551]
Iteration 2: [14.27623368 13.56692041 41.08346551]
Iteration 3: [14.27623368 13.56692041 41.08346551]
Difference: [13.5 13.5 40.5]
Epoch 9/10
Iteration 0: [14.27623368 13.56692041 42.58346551]
Iteration 1: [14.27623368 15.06692041 44.08346551]
Iteration 2: [15.77623368 15.06692041 45.58346551]
Iteration 3: [15.77623368 15.06692041 45.58346551]
Difference: [15. 15. 45.]
Testing:
A:0	B:0	C:0	C_pred:1.0
A:0	B:1	C:0	C_pred:1.0
A:1	B:0	C:0	C_pred:1.0
A:1	B:1	C:1	C_pred:0.0
BCE 36.04365338911715
Score=0.0

## Without bias ReLU

In [43]:
# Main code

# Dividing d_train into data and labels/targets
d_train_y = ANDdata['C']
d_train_X = ANDdata.drop(['C'], axis=1)

    # Dividing d_train into data and labels/targets
d_test_y = ANDdata['C']
d_test_X = ANDdata.drop(['C'], axis=1)

    # Learning rate
alpha = .55

    # Train
weights = perceptron_train(d_train_X, d_train_y, alpha, actfn="relu")

    # Test
result_test = perceptron_test(d_test_X, d_test_y.shape, weights, actfn="relu")

for i in range(len(result_test)):
    print(f"A:{d_test_X.iloc[i][0]}\tB:{d_test_X.iloc[i][1]}\tC:{d_test_y[i]}\tC_pred:{result_test[i]}")


"""from sklearn.metrics import log_loss
print(f"BCE {log_loss(result_test, d_test_y)}")
"""
    # Calculate score
score(result_test, d_test_y)

Epoch 0/10
Iteration 0: [0.48804186 0.74777686]
Iteration 1: [0.48804186 0.74777686]
Iteration 2: [0.48804186 0.74777686]
Iteration 3: [-0.06195814  0.19777686]
Difference: [-0.55 -0.55]
Epoch 1/10
Iteration 0: [-0.06195814  0.19777686]
Iteration 1: [-0.06195814  0.19777686]
Iteration 2: [-0.06195814  0.19777686]
Iteration 3: [-0.61195814 -0.35222314]
Difference: [-1.1 -1.1]
Epoch 2/10
Iteration 0: [-0.61195814 -0.35222314]
Iteration 1: [-0.61195814 -0.35222314]
Iteration 2: [-0.61195814 -0.35222314]
Iteration 3: [-1.16195814 -0.90222314]
Difference: [-1.65 -1.65]
Epoch 3/10
Iteration 0: [-1.16195814 -0.90222314]
Iteration 1: [-1.16195814 -0.90222314]
Iteration 2: [-1.16195814 -0.90222314]
Iteration 3: [-1.71195814 -1.45222314]
Difference: [-2.2 -2.2]
Epoch 4/10
Iteration 0: [-1.71195814 -1.45222314]
Iteration 1: [-1.71195814 -1.45222314]
Iteration 2: [-1.71195814 -1.45222314]
Iteration 3: [-2.26195814 -2.00222314]
Difference: [-2.75 -2.75]
Epoch 5/10
Iteration 0: [-2.26195814 -2.00222314]
Iteration 1: [-2.26195814 -2.00222314]
Iteration 2: [-2.26195814 -2.00222314]
Iteration 3: [-2.81195814 -2.55222314]
Difference: [-3.3 -3.3]
Epoch 6/10
Iteration 0: [-2.81195814 -2.55222314]
Iteration 1: [-2.81195814 -2.55222314]
Iteration 2: [-2.81195814 -2.55222314]
Iteration 3: [-3.36195814 -3.10222314]
Difference: [-3.85 -3.85]
Epoch 7/10
Iteration 0: [-3.36195814 -3.10222314]
Iteration 1: [-3.36195814 -3.10222314]
Iteration 2: [-3.36195814 -3.10222314]
Iteration 3: [-3.91195814 -3.65222314]
Difference: [-4.4 -4.4]
Epoch 8/10
Iteration 0: [-3.91195814 -3.65222314]
Iteration 1: [-3.91195814 -3.65222314]
Iteration 2: [-3.91195814 -3.65222314]
Iteration 3: [-4.46195814 -4.20222314]
Difference: [-4.95 -4.95]
Epoch 9/10
Iteration 0: [-4.46195814 -4.20222314]
Iteration 1: [-4.46195814 -4.20222314]
Iteration 2: [-4.46195814 -4.20222314]
Iteration 3: [-5.01195814 -4.75222314]
Difference: [-5.5 -5.5]
Testing:
A:0	B:0	C:0	C_pred:0.0
A:0	B:1	C:0	C_pred:0.0
A:1	B:0	C:0	C_pred:0.0
A:1	B:1	C:1	C_pred:0.0
Score=75.0

## With bias ReLU

In [44]:
# Main code

# Dividing d_train into data and labels/targets
d_train_y = ANDdata['C']
d_train_X = ANDdata.drop(['C'], axis=1)
d_train_X["bias"] = [1,1,1,1]
    # Dividing d_train into data and labels/targets
d_test_y = d_train_y
d_test_X = d_train_X

    # Learning rate
alpha = .55

    # Train
weights = perceptron_train(d_train_X, d_train_y, alpha, actfn="relu")

    # Test
result_test = perceptron_test(d_test_X, d_test_y.shape, weights, actfn="relu")

for i in range(len(result_test)):
    print(f"A:{d_test_X.iloc[i][0]}\tB:{d_test_X.iloc[i][1]}\tC:{d_test_y[i]}\tC_pred:{result_test[i]}")


"""from sklearn.metrics import log_loss
print(f"BCE {log_loss(result_test, d_test_y)}")
"""
    # Calculate score
score(result_test, d_test_y)

Epoch 0/10
Iteration 0: [0.82131868 0.10749963 0.1693013 ]
Iteration 1: [0.82131868 0.10749963 0.1693013 ]
Iteration 2: [0.82131868 0.10749963 0.1693013 ]
Iteration 3: [ 0.27131868 -0.44250037 -0.3806987 ]
Difference: [-0.55 -0.55 -0.55]
Epoch 1/10
Iteration 0: [ 0.27131868 -0.44250037 -0.3806987 ]
Iteration 1: [ 0.27131868 -0.44250037 -0.3806987 ]
Iteration 2: [ 0.27131868 -0.44250037 -0.3806987 ]
Iteration 3: [-0.27868132 -0.99250037 -0.9306987 ]
Difference: [-1.1 -1.1 -1.1]
Epoch 2/10
Iteration 0: [-0.27868132 -0.99250037 -0.9306987 ]
Iteration 1: [-0.27868132 -0.99250037 -0.9306987 ]
Iteration 2: [-0.27868132 -0.99250037 -0.9306987 ]
Iteration 3: [-0.82868132 -1.54250037 -1.4806987 ]
Difference: [-1.65 -1.65 -1.65]
Epoch 3/10
Iteration 0: [-0.82868132 -1.54250037 -1.4806987 ]
Iteration 1: [-0.82868132 -1.54250037 -1.4806987 ]
Iteration 2: [-0.82868132 -1.54250037 -1.4806987 ]
Iteration 3: [-1.37868132 -2.09250037 -2.0306987 ]
Difference: [-2.2 -2.2 -2.2]
Epoch 4/10
Iteration 0: [-1.37868132 -2.09250037 -2.0306987 ]
Iteration 1: [-1.37868132 -2.09250037 -2.0306987 ]
Iteration 2: [-1.37868132 -2.09250037 -2.0306987 ]
Iteration 3: [-1.92868132 -2.64250037 -2.5806987 ]
Difference: [-2.75 -2.75 -2.75]
Epoch 5/10
Iteration 0: [-1.92868132 -2.64250037 -2.5806987 ]
Iteration 1: [-1.92868132 -2.64250037 -2.5806987 ]
Iteration 2: [-1.92868132 -2.64250037 -2.5806987 ]
Iteration 3: [-2.47868132 -3.19250037 -3.1306987 ]
Difference: [-3.3 -3.3 -3.3]
Epoch 6/10
Iteration 0: [-2.47868132 -3.19250037 -3.1306987 ]
Iteration 1: [-2.47868132 -3.19250037 -3.1306987 ]
Iteration 2: [-2.47868132 -3.19250037 -3.1306987 ]
Iteration 3: [-3.02868132 -3.74250037 -3.6806987 ]
Difference: [-3.85 -3.85 -3.85]
Epoch 7/10
Iteration 0: [-3.02868132 -3.74250037 -3.6806987 ]
Iteration 1: [-3.02868132 -3.74250037 -3.6806987 ]
Iteration 2: [-3.02868132 -3.74250037 -3.6806987 ]
Iteration 3: [-3.57868132 -4.29250037 -4.2306987 ]
Difference: [-4.4 -4.4 -4.4]
Epoch 8/10
Iteration 0: [-3.57868132 -4.29250037 -4.2306987 ]
Iteration 1: [-3.57868132 -4.29250037 -4.2306987 ]
Iteration 2: [-3.57868132 -4.29250037 -4.2306987 ]
Iteration 3: [-4.12868132 -4.84250037 -4.7806987 ]
Difference: [-4.95 -4.95 -4.95]
Epoch 9/10
Iteration 0: [-4.12868132 -4.84250037 -4.7806987 ]
Iteration 1: [-4.12868132 -4.84250037 -4.7806987 ]
Iteration 2: [-4.12868132 -4.84250037 -4.7806987 ]
Iteration 3: [-4.67868132 -5.39250037 -5.3306987 ]
Difference: [-5.5 -5.5 -5.5]
Testing:
A:0	B:0	C:0	C_pred:0.0
A:0	B:1	C:0	C_pred:0.0
A:1	B:0	C:0	C_pred:0.0
A:1	B:1	C:1	C_pred:0.0
Score=75.0

# Non Linear dataset

## Without bias sigmoid

In [9]:
# Dividing d_train into data and labels/targets
d_train_y = XORdata['C']
d_train_X = XORdata.drop(['C'], axis=1)

    # Dividing d_train into data and labels/targets
d_test_y = XORdata['C']
d_test_X = XORdata.drop(['C'], axis=1)

    # Learning rate
alpha = 0.5

    # Train
weights = perceptron_train(d_train_X, d_train_y, alpha,actfn = "sigmoid")

    # Test
result_test = perceptron_test(d_test_X, d_test_y.shape, weights,actfn="sigmoid")

for i in range(len(result_test)):
    print(f"A:{d_test_X.iloc[i][0]}\tB:{d_test_X.iloc[i][1]}\tC:{d_test_y[i]}\tC_pred:{result_test[i]}")

# Calculate score
score(result_test, d_test_y)

Epoch 0/10
Iteration 0: [0.01119419 0.99654607]
Iteration 1: [0.01119419 0.99654607]
Iteration 2: [0.01119419 0.99654607]
Iteration 3: [0.51119419 1.49654607]
Difference: [0.5 0.5]
Epoch 1/10
Iteration 0: [0.51119419 1.49654607]
Iteration 1: [0.51119419 1.49654607]
Iteration 2: [0.51119419 1.49654607]
Iteration 3: [1.01119419 1.99654607]
Difference: [1. 1.]
Epoch 2/10
Iteration 0: [1.01119419 1.99654607]
Iteration 1: [1.01119419 1.99654607]
Iteration 2: [1.01119419 1.99654607]
Iteration 3: [1.51119419 2.49654607]
Difference: [1.5 1.5]
Epoch 3/10
Iteration 0: [1.51119419 2.49654607]
Iteration 1: [1.51119419 2.49654607]
Iteration 2: [1.51119419 2.49654607]
Iteration 3: [2.01119419 2.99654607]
Difference: [2. 2.]
Epoch 4/10
Iteration 0: [2.01119419 2.99654607]
Iteration 1: [2.01119419 2.99654607]
Iteration 2: [2.01119419 2.99654607]
Iteration 3: [2.51119419 3.49654607]
Difference: [2.5 2.5]
Epoch 5/10
Iteration 0: [2.51119419 3.49654607]
Iteration 1: [2.51119419 3.49654607]
Iteration 2: [2.51119419 3.49654607]
Iteration 3: [3.01119419 3.99654607]
Difference: [3. 3.]
Epoch 6/10
Iteration 0: [3.01119419 3.99654607]
Iteration 1: [3.01119419 3.99654607]
Iteration 2: [3.01119419 3.99654607]
Iteration 3: [3.51119419 4.49654607]
Difference: [3.5 3.5]
Epoch 7/10
Iteration 0: [3.51119419 4.49654607]
Iteration 1: [3.51119419 4.49654607]
Iteration 2: [3.51119419 4.49654607]
Iteration 3: [4.01119419 4.99654607]
Difference: [4. 4.]
Epoch 8/10
Iteration 0: [4.01119419 4.99654607]
Iteration 1: [4.01119419 4.99654607]
Iteration 2: [4.01119419 4.99654607]
Iteration 3: [4.51119419 5.49654607]
Difference: [4.5 4.5]
Epoch 9/10
Iteration 0: [4.51119419 5.49654607]
Iteration 1: [4.51119419 5.49654607]
Iteration 2: [4.51119419 5.49654607]
Iteration 3: [5.01119419 5.99654607]
Difference: [5. 5.]
Testing:
A:0	B:0	C:0	C_pred:1.0
A:0	B:1	C:1	C_pred:1.0
A:1	B:0	C:1	C_pred:0.0
A:1	B:1	C:0	C_pred:0.0
Score=50.0

## Without bias tanh

In [10]:
# Dividing d_train into data and labels/targets
d_train_y = XORdata['C']
d_train_X = XORdata.drop(['C'], axis=1)

    # Dividing d_train into data and labels/targets
d_test_y = XORdata['C']
d_test_X = XORdata.drop(['C'], axis=1)

    # Learning rate
alpha = 0.5

    # Train
weights = perceptron_train(d_train_X, d_train_y, alpha,actfn = "tanh")

    # Test
result_test = perceptron_test(d_test_X, d_test_y.shape, weights,actfn="tanh")

for i in range(len(result_test)):
    print(f"A:{d_test_X.iloc[i][0]}\tB:{d_test_X.iloc[i][1]}\tC:{d_test_y[i]}\tC_pred:{result_test[i]}")

# Calculate score
score(result_test, d_test_y)

Epoch 0/10
Iteration 0: [0.84413895 0.40023156]
Iteration 1: [0.84413895 0.40023156]
Iteration 2: [0.84413895 0.40023156]
Iteration 3: [1.34413895 0.90023156]
Difference: [0.5 0.5]
Epoch 1/10
Iteration 0: [1.34413895 0.90023156]
Iteration 1: [1.34413895 0.90023156]
Iteration 2: [1.34413895 0.90023156]
Iteration 3: [1.84413895 1.40023156]
Difference: [1. 1.]
Epoch 2/10
Iteration 0: [1.84413895 1.40023156]
Iteration 1: [1.84413895 1.40023156]
Iteration 2: [1.84413895 1.40023156]
Iteration 3: [2.34413895 1.90023156]
Difference: [1.5 1.5]
Epoch 3/10
Iteration 0: [2.34413895 1.90023156]
Iteration 1: [2.34413895 1.90023156]
Iteration 2: [2.34413895 1.90023156]
Iteration 3: [2.84413895 2.40023156]
Difference: [2. 2.]
Epoch 4/10
Iteration 0: [2.84413895 2.40023156]
Iteration 1: [2.84413895 2.40023156]
Iteration 2: [2.84413895 2.40023156]
Iteration 3: [3.34413895 2.90023156]
Difference: [2.5 2.5]
Epoch 5/10
Iteration 0: [3.34413895 2.90023156]
Iteration 1: [3.34413895 2.90023156]
Iteration 2: [3.34413895 2.90023156]
Iteration 3: [3.84413895 3.40023156]
Difference: [3. 3.]
Epoch 6/10
Iteration 0: [3.84413895 3.40023156]
Iteration 1: [3.84413895 3.40023156]
Iteration 2: [3.84413895 3.40023156]
Iteration 3: [4.34413895 3.90023156]
Difference: [3.5 3.5]
Epoch 7/10
Iteration 0: [4.34413895 3.90023156]
Iteration 1: [4.34413895 3.90023156]
Iteration 2: [4.34413895 3.90023156]
Iteration 3: [4.84413895 4.40023156]
Difference: [4. 4.]
Epoch 8/10
Iteration 0: [4.84413895 4.40023156]
Iteration 1: [4.84413895 4.40023156]
Iteration 2: [4.84413895 4.40023156]
Iteration 3: [5.34413895 4.90023156]
Difference: [4.5 4.5]
Epoch 9/10
Iteration 0: [5.34413895 4.90023156]
Iteration 1: [5.34413895 4.90023156]
Iteration 2: [5.34413895 4.90023156]
Iteration 3: [5.84413895 5.40023156]
Difference: [5. 5.]
Testing:
A:0	B:0	C:0	C_pred:0.0
A:0	B:1	C:1	C_pred:1.0
A:1	B:0	C:1	C_pred:0.0
A:1	B:1	C:0	C_pred:0.0
Score=75.0

## Without bias ReLU

In [11]:
# Dividing d_train into data and labels/targets
d_train_y = XORdata['C']
d_train_X = XORdata.drop(['C'], axis=1)

    # Dividing d_train into data and labels/targets
d_test_y = XORdata['C']
d_test_X = XORdata.drop(['C'], axis=1)

    # Learning rate
alpha = 0.5

    # Train
weights = perceptron_train(d_train_X, d_train_y, alpha,actfn = "relu")

    # Test
result_test = perceptron_test(d_test_X, d_test_y.shape, weights,actfn="relu")

for i in range(len(result_test)):
    print(f"A:{d_test_X.iloc[i][0]}\tB:{d_test_X.iloc[i][1]}\tC:{d_test_y[i]}\tC_pred:{result_test[i]}")

# Calculate score
score(result_test, d_test_y)

Epoch 0/10
Iteration 0: [0.01633796 0.21309911]
Iteration 1: [ 0.01633796 -0.28690089]
Iteration 2: [-0.48366204 -0.28690089]
Iteration 3: [-0.48366204 -0.28690089]
Difference: [-0.5 -0.5]
Epoch 1/10
Iteration 0: [-0.48366204 -0.28690089]
Iteration 1: [-0.48366204 -0.78690089]
Iteration 2: [-0.98366204 -0.78690089]
Iteration 3: [-0.98366204 -0.78690089]
Difference: [-1. -1.]
Epoch 2/10
Iteration 0: [-0.98366204 -0.78690089]
Iteration 1: [-0.98366204 -1.28690089]
Iteration 2: [-1.48366204 -1.28690089]
Iteration 3: [-1.48366204 -1.28690089]
Difference: [-1.5 -1.5]
Epoch 3/10
Iteration 0: [-1.48366204 -1.28690089]
Iteration 1: [-1.48366204 -1.78690089]
Iteration 2: [-1.98366204 -1.78690089]
Iteration 3: [-1.98366204 -1.78690089]
Difference: [-2. -2.]
Epoch 4/10
Iteration 0: [-1.98366204 -1.78690089]
Iteration 1: [-1.98366204 -2.28690089]
Iteration 2: [-2.48366204 -2.28690089]
Iteration 3: [-2.48366204 -2.28690089]
Difference: [-2.5 -2.5]
Epoch 5/10
Iteration 0: [-2.48366204 -2.28690089]
Iteration 1: [-2.48366204 -2.78690089]
Iteration 2: [-2.98366204 -2.78690089]
Iteration 3: [-2.98366204 -2.78690089]
Difference: [-3. -3.]
Epoch 6/10
Iteration 0: [-2.98366204 -2.78690089]
Iteration 1: [-2.98366204 -3.28690089]
Iteration 2: [-3.48366204 -3.28690089]
Iteration 3: [-3.48366204 -3.28690089]
Difference: [-3.5 -3.5]
Epoch 7/10
Iteration 0: [-3.48366204 -3.28690089]
Iteration 1: [-3.48366204 -3.78690089]
Iteration 2: [-3.98366204 -3.78690089]
Iteration 3: [-3.98366204 -3.78690089]
Difference: [-4. -4.]
Epoch 8/10
Iteration 0: [-3.98366204 -3.78690089]
Iteration 1: [-3.98366204 -4.28690089]
Iteration 2: [-4.48366204 -4.28690089]
Iteration 3: [-4.48366204 -4.28690089]
Difference: [-4.5 -4.5]
Epoch 9/10
Iteration 0: [-4.48366204 -4.28690089]
Iteration 1: [-4.48366204 -4.78690089]
Iteration 2: [-4.98366204 -4.78690089]
Iteration 3: [-4.98366204 -4.78690089]
Difference: [-5. -5.]
Testing:
A:0	B:0	C:0	C_pred:0.0
A:0	B:1	C:1	C_pred:0.0
A:1	B:0	C:1	C_pred:0.0
A:1	B:1	C:0	C_pred:0.0
Score=50.0